sonar.projectKey=Noahffiliation_trakt-calendar
sonar.organization=noahffiliation

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/*
sonar.test.exclusions=tests/*
sonar.python.version=3.13
