sonar.projectKey=Noahffiliation_trakt-calendar
sonar.organization=noahffiliation

sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.cpd.exclusions=tests/**
sonar.python.version=3.13
