name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read
  security-events: write

jobs:
  python-ci:
    uses: Noahffiliation/.github/.github/workflows/reusable-python-ci.yml@main
    with:
      python-version: "3.12.3"
      test-docker: true
    secrets: inherit
